### ISSUE TITLE
React 17 peer dependency

### ISSUE THREAD

**Issue by browniebroke** [browniebroke/gatsby-image-gallery#629]
Although it works fine (AFAIK), when installing on a project running React 17, we have these warnings:

```
warning "@browniebroke/gatsby-image-gallery > react-image-lightbox@5.1.1" has incorrect peer dependency "react@^16.x".
warning "@browniebroke/gatsby-image-gallery > react-image-lightbox@5.1.1" has incorrect peer dependency "react-dom@^16.x".
```

The `react-image-lightbox` dependency hasn't been updated in a while, might consider switching to another one if the situation persists. I will list here some interesting options as I find them:

- https://github.com/michelecocuccio/simple-react-lightbox
- https://github.com/banthagroup/fslightbox-react

**Comment by wildpow** [comment]
Had a similar issue with react-move but, it's another almost unmaintained project and my PR is collecting dust.
I am building a project that needs an image gallery just like this project but, most examples I've found use either unmaintained modules or the old `gatsby-image`. I was going to fork [react-awsome-lightbox](https://github.com/theanam/react-awesome-lightbox) (because it looks somewhat maintained) to work with `gatsby-image-plugin` but, this project may do nicely.

P.S [PR for react-image-lightbox](https://github.com/frontend-collective/react-image-lightbox/pull/423).

**Comment by wildpow** [comment]
Well tried out `simple-react-lightbox` and there is a lot to like. For instance, I get to keep my custom masonry gallery and get a lightbox/carousel almost for free just put it in between provide HOC, and done. Unfortunately, this package bundle is huge! Vscode estimates 298K before gzip effectively doubling my bundle size of the small site I'm working on which is a non-starter for me personally. 

 [PR #142](https://github.com/michelecocuccio/simple-react-lightbox/pull/142) seem to shave 50Kb by changing lodash imports but even 240Kb is a tough pill to swallow.
